### ISSUE TITLE
ServiceMonitor for Prometheus Operator having trouble scrapping metrics

### ISSUE THREAD

**Issue by Luks24** [k3rnelpan1c-dev/uptime-kuma-helm#155]
I'm writing here since I spent a couple of days without luck trying to find a solution to my problem. I want to scrape metrics from the **/metrics** endpoint of uptime-kuma. For this, I'm using the Prometheus operator. I tried to configure the ServiceMonitor like this:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma-test
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: uptime-kuma
  namespaceSelector:
    matchNames:
      - uptime-kuma
  endpoints:
    - interval: 30s
      targetPort: 3001
      port: "http"
      path: /metrics
  jobLabel: "uptime"
```
I first had authentication enabled but have since then disabled it. I can also see in Prometheus that the target was found ( I can see the name of the pod and all relevant information ) but the status of the target is Dropped.

I am probably doing something wrong but don't know what. Has anybody else encountered the same problem ?

**Comment by k3rnelpan1c-dev** [comment]
Hmm, while I do not feel responsible for the metrics feature of `uptime-kuma` I have had my fair share of this sort of problems in the past with other deployments.
Unfortunately, I cannot recall exactly what it was that I ended up doing to fix them (but it might have had something to do with the label selector, at least back with those occurrences).

I will permit this Issue to be open here, and hope that the community may be able to help (i.e. someone with a similar setup), but I can unfortunately not be of any help right now.

**Comment by Luks24** [comment]
I resolved this later and wanted to share the answer if somebody else encounters the same problem. So I created this ServiceMonitor inside the monitoring namespace where I have the Prometheus operator deployed. Uptime kuma runs in the **uptime-kuma** namespace that also has the same label.

This yaml is now working. As far as I remember the issue was with the property that matched the label. Using **app.kubernetes.io/name** fixed the issue for me.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      targetPort: 3001
      port: "http"
      path: /metrics
  namespaceSelector:
    matchNames:
      - uptime-kuma
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
  jobLabel: "uptime"
```
