### ISSUE TITLE
Enable probes tweaking

### ISSUE THREAD

**Issue by kikinsama** [k3rnelpan1c-dev/uptime-kuma-helm#164]
On slower filesystems the database migration takes a while and the readiness probe kills the pod before the migration can finish.

Adding support to configure something like this would be tremendously helpful:

```
readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 5
```
